# Generated by Django 3.2.4 on 2021-06-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
    ]
