# Generated by Django 3.2.4 on 2021-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
